import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../../components/Navbar'
import HomeCarousel from '../../components/HomeCarousel'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar></Navbar>
      <main className={styles.main}>
        <section className={styles.homeHeader}>
          <HomeCarousel></HomeCarousel>
        </section>
        <section className={styles.homeReasons}></section>
        <section className={styles.homePortfolio}></section>
      </main>
    </>
  )
}
